package inciobot.bot_backend.enums;

public enum FifaConversationSecondStage {
	SELECT_OPPONENT, INSERT_RESULT, CONFIRM_RESULT, INSERT_MATCH_ID,
	// stats
	SELECT_STATISTICS_TYPE, SELECT_STATISTICS_COMPARISON, SELECT_STAT_FIRST_OPPONENT, SELECT_STAT_TYPE_FIRST_OPPONENT, SELECT_STAT_SECOND_OPPONENT, STATISTICS_ALL, STATISTIC_SPECIFIC_USER,

	INSERT_COMMENT, INSERT_DATE, INSERT_HOUR;
}
